### ISSUE TITLE
root title is incorrect

### ISSUE THREAD

**Issue by samthomson** [status-im/incubate.status.im#7]
the main index page title is still Nimbus, it could be changed to Incubate

**Comment by samthomson** [comment]
not sure if you're intentionally waiting to merge develop to master for this site and studio which still has the old title (that got updated in a previous PR) until merged with its master. (just commenting in case you forgot to what with the devcon distractions :smile: )

**Comment by andytudhope** [comment]
Was merged to `master` here: https://github.com/status-im/incubate.status.im/pull/6

Will follow up in Studio now too, thanks for the reminder.
